{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d44798f8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/Users/dodo/SuperDuperDB/pinnacledb\n"
     ]
    }
   ],
   "source": [
    "cd .."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "af3bf038",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{\r\n",
      "    \"distributed\": true,\r\n",
      "    \"dask\": {\"local\": true}\r\n",
      "}\r\n"
     ]
    }
   ],
   "source": [
    "!cat configs.json"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "34229af6",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'apis': {'providers': {},\n",
      "          'retry': {'stop_after_attempt': 2,\n",
      "                    'wait_max': 10.0,\n",
      "                    'wait_min': 4.0,\n",
      "                    'wait_multiplier': 1.0}},\n",
      " 'cdc': False,\n",
      " 'dask': {'deserializers': [],\n",
      "          'ip': 'localhost',\n",
      "          'local': True,\n",
      "          'password': '',\n",
      "          'port': 8786,\n",
      "          'serializers': [],\n",
      "          'username': ''},\n",
      " 'data_layers': {'artifact': {'cls': 'mongodb',\n",
      "                              'connection': 'pymongo',\n",
      "                              'kwargs': {'host': 'localhost',\n",
      "                                         'password': 'testmongodbpassword',\n",
      "                                         'port': 27018,\n",
      "                                         'username': 'testmongodbuser'},\n",
      "                              'name': '_filesystem:test_db'},\n",
      "                 'data_backend': {'cls': 'mongodb',\n",
      "                                  'connection': 'pymongo',\n",
      "                                  'kwargs': {'host': 'localhost',\n",
      "                                             'password': 'testmongodbpassword',\n",
      "                                             'port': 27018,\n",
      "                                             'username': 'testmongodbuser'},\n",
      "                                  'name': 'test_db'},\n",
      "                 'metadata': {'cls': 'mongodb',\n",
      "                              'connection': 'pymongo',\n",
      "                              'kwargs': {'host': 'localhost',\n",
      "                                         'password': 'testmongodbpassword',\n",
      "                                         'port': 27018,\n",
      "                                         'username': 'testmongodbuser'},\n",
      "                              'name': 'test_db'}},\n",
      " 'distributed': True,\n",
      " 'logging': {'kwargs': {},\n",
      "             'level': <LogLevel.INFO: 'INFO'>,\n",
      "             'type': <LogType.STDERR: 'STDERR'>},\n",
      " 'model_server': {'host': '127.0.0.1',\n",
      "                  'password': '',\n",
      "                  'port': 5001,\n",
      "                  'username': ''},\n",
      " 'notebook': {'ip': '0.0.0.0', 'password': '', 'port': 8888, 'token': ''},\n",
      " 'ray': {'deployments': [],\n",
      "         'host': '127.0.0.1',\n",
      "         'password': '',\n",
      "         'port': 0,\n",
      "         'username': ''},\n",
      " 'server': {'host': '127.0.0.1', 'port': 3223, 'protocol': 'http'},\n",
      " 'vector_search': {'host': 'localhost',\n",
      "                   'password': '',\n",
      "                   'port': 19530,\n",
      "                   'type': {'backfill_batch_size': 100, 'inmemory': True},\n",
      "                   'username': ''}}\n"
     ]
    }
   ],
   "source": [
    "from pinnacledb import CFG\n",
    "\n",
    "import pprint\n",
    "pprint.pprint(CFG.dict())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "9d334809",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:numexpr.utils:NumExpr defaulting to 8 threads.\n",
      "INFO:distributed.http.proxy:To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy\n",
      "INFO:distributed.scheduler:State start\n",
      "INFO:distributed.diskutils:Found stale lock file and directory '/var/folders/y9/b74b9yj906s_wtj0rrh2lf7c0000gn/T/dask-scratch-space/worker-jgs3cy1k', purging\n",
      "INFO:distributed.scheduler:  Scheduler at:     tcp://127.0.0.1:62805\n",
      "INFO:distributed.scheduler:  dashboard at:  http://127.0.0.1:8787/status\n",
      "INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:62808'\n",
      "INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:62809'\n",
      "INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:62810'\n",
      "INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:62811'\n",
      "INFO:distributed.scheduler:Register worker <WorkerState 'tcp://127.0.0.1:62816', name: 0, status: init, memory: 0, processing: 0>\n",
      "INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:62816\n",
      "INFO:distributed.core:Starting established connection to tcp://127.0.0.1:62819\n",
      "INFO:distributed.scheduler:Register worker <WorkerState 'tcp://127.0.0.1:62818', name: 1, status: init, memory: 0, processing: 0>\n",
      "INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:62818\n",
      "INFO:distributed.core:Starting established connection to tcp://127.0.0.1:62822\n",
      "INFO:distributed.scheduler:Register worker <WorkerState 'tcp://127.0.0.1:62820', name: 2, status: init, memory: 0, processing: 0>\n",
      "INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:62820\n",
      "INFO:distributed.core:Starting established connection to tcp://127.0.0.1:62825\n",
      "INFO:distributed.scheduler:Register worker <WorkerState 'tcp://127.0.0.1:62823', name: 3, status: init, memory: 0, processing: 0>\n",
      "INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:62823\n",
      "INFO:distributed.core:Starting established connection to tcp://127.0.0.1:62827\n",
      "INFO:distributed.scheduler:Receive client connection: Client-7d0a1888-2bee-11ee-bd44-1e00f226d550\n",
      "INFO:distributed.core:Starting established connection to tcp://127.0.0.1:62828\n"
     ]
    }
   ],
   "source": [
    "from pinnacledb.datalayer.base.build import build_datalayer\n",
    "\n",
    "db = build_datalayer()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "71a538ce",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:root:Could not get an identifier from submitted function, creating one!\n",
      "INFO:distributed.http.proxy:To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy\n",
      "/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.\n",
      "Perhaps you already have a cluster running?\n",
      "Hosting the HTTP server on port 62844 instead\n",
      "  warnings.warn(\n",
      "INFO:distributed.scheduler:State start\n",
      "INFO:distributed.scheduler:  Scheduler at:     tcp://127.0.0.1:62845\n",
      "INFO:distributed.scheduler:  dashboard at:  http://127.0.0.1:62844/status\n",
      "2023-07-26 15:56:25,753 - distributed.nanny - ERROR - Failed to start process\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/nanny.py\", line 432, in instantiate\n",
      "    result = await self.process.start()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/nanny.py\", line 720, in start\n",
      "    await self.process.start()\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/process.py\", line 55, in _call_and_set_future\n",
      "    res = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/process.py\", line 215, in _start\n",
      "    process.start()\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py\", line 118, in start\n",
      "    assert not _current_process._config.get('daemon'), \\\n",
      "AssertionError: daemonic processes are not allowed to have children\n",
      "ERROR:distributed.nanny:Failed to start process\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/nanny.py\", line 432, in instantiate\n",
      "    result = await self.process.start()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/nanny.py\", line 720, in start\n",
      "    await self.process.start()\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/process.py\", line 55, in _call_and_set_future\n",
      "    res = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/process.py\", line 215, in _start\n",
      "    process.start()\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py\", line 118, in start\n",
      "    assert not _current_process._config.get('daemon'), \\\n",
      "AssertionError: daemonic processes are not allowed to have children\n",
      "2023-07-26 15:56:25,754 - distributed.nanny - ERROR - Failed to start process\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/nanny.py\", line 432, in instantiate\n",
      "    result = await self.process.start()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/nanny.py\", line 720, in start\n",
      "    await self.process.start()\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/process.py\", line 55, in _call_and_set_future\n",
      "    res = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/process.py\", line 215, in _start\n",
      "    process.start()\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py\", line 118, in start\n",
      "    assert not _current_process._config.get('daemon'), \\\n",
      "AssertionError: daemonic processes are not allowed to have children\n",
      "ERROR:distributed.nanny:Failed to start process\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/nanny.py\", line 432, in instantiate\n",
      "    result = await self.process.start()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/nanny.py\", line 720, in start\n",
      "    await self.process.start()\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/process.py\", line 55, in _call_and_set_future\n",
      "    res = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/process.py\", line 215, in _start\n",
      "    process.start()\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py\", line 118, in start\n",
      "    assert not _current_process._config.get('daemon'), \\\n",
      "AssertionError: daemonic processes are not allowed to have children\n",
      "2023-07-26 15:56:25,755 - distributed.nanny - ERROR - Failed to start process\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/nanny.py\", line 432, in instantiate\n",
      "    result = await self.process.start()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/nanny.py\", line 720, in start\n",
      "    await self.process.start()\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/process.py\", line 55, in _call_and_set_future\n",
      "    res = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/process.py\", line 215, in _start\n",
      "    process.start()\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py\", line 118, in start\n",
      "    assert not _current_process._config.get('daemon'), \\\n",
      "AssertionError: daemonic processes are not allowed to have children\n",
      "ERROR:distributed.nanny:Failed to start process\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/nanny.py\", line 432, in instantiate\n",
      "    result = await self.process.start()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/nanny.py\", line 720, in start\n",
      "    await self.process.start()\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/process.py\", line 55, in _call_and_set_future\n",
      "    res = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/process.py\", line 215, in _start\n",
      "    process.start()\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py\", line 118, in start\n",
      "    assert not _current_process._config.get('daemon'), \\\n",
      "AssertionError: daemonic processes are not allowed to have children\n",
      "2023-07-26 15:56:25,756 - distributed.nanny - ERROR - Failed to start process\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/nanny.py\", line 432, in instantiate\n",
      "    result = await self.process.start()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/nanny.py\", line 720, in start\n",
      "    await self.process.start()\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/process.py\", line 55, in _call_and_set_future\n",
      "    res = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/process.py\", line 215, in _start\n",
      "    process.start()\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py\", line 118, in start\n",
      "    assert not _current_process._config.get('daemon'), \\\n",
      "AssertionError: daemonic processes are not allowed to have children\n",
      "ERROR:distributed.nanny:Failed to start process\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/nanny.py\", line 432, in instantiate\n",
      "    result = await self.process.start()\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/nanny.py\", line 720, in start\n",
      "    await self.process.start()\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/process.py\", line 55, in _call_and_set_future\n",
      "    res = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/dodo/SuperDuperDB/pinnacledb/.venv/lib/python3.11/site-packages/distributed/process.py\", line 215, in _start\n",
      "    process.start()\n",
      "  File \"/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py\", line 118, in start\n",
      "    assert not _current_process._config.get('daemon'), \\\n",
      "AssertionError: daemonic processes are not allowed to have children\n"
     ]
    }
   ],
   "source": [
    "import pymongo\n",
    "import torch\n",
    "\n",
    "from pinnacledb import pinnacle\n",
    "from pinnacledb.core.document import Document as D\n",
    "from pinnacledb.encoders.torch.tensor import tensor\n",
    "from pinnacledb.datalayer.mongodb.query import Collection\n",
    "\n",
    "m = pinnacle(\n",
    "    torch.nn.Linear(128, 7),\n",
    "    encoder=tensor(torch.float, shape=(7,))\n",
    ")\n",
    "\n",
    "t32 = tensor(torch.float, shape=(128,))\n",
    "\n",
    "output = db.execute(\n",
    "    Collection('localcluster').insert_many(\n",
    "        [D({'x': t32(torch.randn(128))}) for _ in range(1000)], \n",
    "        encoders=(t32,)\n",
    "    )\n",
    ")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
